force-app/main/default/objects/Timesheet_Entry__c/Timesheet_Entry__c.object-meta.xml
<CustomObject>
    <label>Timesheet Entry</label>
    <nameField>
        <displayFormat>TE-{0000000}</displayFormat>
        <label>Timesheet Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet_Entry__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recruitment</fullName>
            </value>
            <value>
                <fullName>Screening</fullName>
            </value>
            <value>
                <fullName>Training of Mentors and Mentees</fullName>
            </value>
            <value>
                <fullName>Matching and Initiating</fullName>
            </value>
            <value>
                <fullName>Monitoring and Support</fullName>
            </value>
            <value>
                <fullName>Closure</fullName>
            </value>
            <value>
                <fullName>Program Operations</fullName>
            </value>
            <value>
                <fullName>Program Planning and Management</fullName>
            </value>
            <value>
                <fullName>Program Evaluation</fullName>
            </value>
            <value>
                <fullName>Delivery of Train the trainer</fullName>
            </value>
            <value>
                <fullName>Prepare Program for NQMS</fullName>
            </value>
            <value>
                <fullName>Guide through NQMS Self-Assessment</fullName>
            </value>
            <value>
                <fullName>NQMS Review</fullName>
            </value>
            <value>
                <fullName>NQMS I&amp;I Plan</fullName>
            </value>
            <value>
                <fullName>NQMS Follow up TA</fullName>
            </value>
            <value>
                <fullName>Support addition of a program to Mentoring Connector</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Consultant Model</fullName>
            </value>
            <value>
                <fullName>TA Provider Learning- List Name</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Timesheet_Entry__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Timesheet Entries</relationshipLabel>
    <relationshipName>Timesheet_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/timesheetmanagement_Test.cls
@isTest
private class timesheetmanagement_Test{
    
    @TestSetup
    public static void setup(){
        Case caseObj = new Case();
        insert caseObj;
        List<Timesheet_Entry__c> lstTimesheets = new List<Timesheet_Entry__c>();
        Timesheet_Entry__c drTimesheet_Entry=new Timesheet_Entry__c(Program__c='Recruitment',Week_Start_Date__c=Date.today());
        Timesheet_Entry__c drTimesheet_Entry2=new Timesheet_Entry__c(Program__c='Recruitment',Week_Start_Date__c=Date.today().toStartofWeek()+1, Request__c=caseObj.Id);
        lstTimesheets.add(drTimesheet_Entry);
        lstTimesheets.add(drTimesheet_Entry2);
        Database.insert(lstTimesheets,false);
    }
    
    @isTest
    private static void onloadfunction_Test(){
        Case caseObj = [select Id from Case Limit 1];
        Test.startTest();
        timesheetmanagement obj = new timesheetmanagement(null);
        obj.caseId = caseObj.Id;
        obj.onloadfunction();
        obj.timesheetEntry.Week_Start_Date__c = System.today().toStartofWeek()+1;
        obj.timesheetEntry.Program__c = 'Screening';
        obj.otherentries = new List<Timesheet_Entry__c>{obj.timesheetEntry};
        obj.onloadfunction();
        Test.stopTest();
    }
    @isTest
    private static void getotherentrylist_Test(){
        Test.startTest();
        timesheetmanagement obj = new timesheetmanagement(null);
        obj.getotherentrylist();
        Test.stopTest();
    }
    @isTest
    private static void addrowothers_Test(){
        Test.startTest();
        timesheetmanagement obj = new timesheetmanagement(null);
        obj.addrowothers();
        Test.stopTest();
    }
    @isTest
    private static void savetimesheet_Test(){
        Case caseObj = [select Id from Case Limit 1];
        Test.startTest();
        timesheetmanagement obj = new timesheetmanagement(null);
        obj.caseId = caseObj.Id;
        obj.onloadfunction();
        obj.timesheetEntry.Week_Start_Date__c = System.TODAY();
        obj.timesheetEntry.Program__c = 'Recruitment';
        obj.otherentries = new List<Timesheet_Entry__c>{obj.timesheetEntry,obj.timesheetEntry};
        obj.savetimesheet();
        Test.stopTest();
    }
    @isTest
    private static void sumDoubles_Test(){
        Test.startTest();
        timesheetmanagement obj = new timesheetmanagement(null);
        obj.sumDoubles(1.1,1.1);
        obj = new timesheetmanagement(null);
        obj.sumDoubles(null,1.1);
        Test.stopTest();
    }
}